version: '3.3'
services:
    api:
        build:
            context: .
            dockerfile: adonisjs.dockerfile
        container_name: adonisjs
        ports:
            - "8082:8082"
        volumes:
            - ./api:/home
        stdin_open: true
        tty: true